name: coworking_space
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # image_picker: ^0.6.5+2
  # image_cropper: ^1.2.1
  # observable: ^0.23.0
  # rxdart: 
 
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3    
  # if you are using latest flutter please update your flutter_svg package to ^0.18.*
  # flutter_svg: ^0.19.1 # help us to use SVG in our app
  # for State management  
  
  # --- after change  shruti
  flutter_rating_bar: ^4.0.0
  # switch for price
  flutter_switch: ^0.0.2
  carousel_pro: ^1.0.0  
  carousel_slider: ^1.3.0  
  datetime_picker_formfield: ^2.0.0
  toggle_switch: ^0.1.9  
  # for payment gateway razorpay
  razorpay_flutter: ^1.2.3
  fluttertoast: ^7.1.6

# 13-5-2021
  
  ## geoflutterfire: ^2.2.2 depend o fire store 0.16 not posible  
  
  # inded# -----------------------
  permission_handler: ^6.1.1 
  location : ^4.0.0  
  # geoflutterfire: ^3.0.0-nullsafety.2
  geolocator: ^5.3.0
  # -----------------------
  # geolocator: ^5.3.1  
  # geolocator: ^4.0.3
  # carousel_slider: ^3.0.0
    
  # for google map package
  google_maps_flutter: ^0.5.21
  url_launcher: ^5.1.3
  dotted_line: ^3.0.0
  
  # new flutter depedencies this is running app on 17-4-2021 final 
  # firebase_core:    
  # firebase_core: 
  # firebase_auth: 
  # cloud_firestore: 

  # firebase_storage: ^8.0.2
  http: ^0.13.0
  intl: ^0.17.0
  # flutter_svg: ^0.19.3 mine svg
  # firebase_analytics: ^7.1.1

#today error solvig  0n 17-4-2021

# janu login register scrren

  firebase_core: ^0.3.4 
  firebase_auth: ^0.8.4+4
  cloud_firestore: ^0.9.13+1
  
    # login for new 
  # firebase_auth: ^0.15.2
  # firebase_auth: ^0.16.1
  # cloud_firestore: ^0.13.7
  shared_preferences:
  provider: 
  flutter_settings_screens:  
  pinput: ^0.2.6
  geoflutterfire: 
  flutter_local_notifications: 
  firebase_messaging: 
  form_field_validator: 
  modal_progress_hud: 
  # firebase_messaging:  
  # firebase_messaging: ^4.0.0+1     /// -for old noti

  # syncfusion_flutter_pdf: ^19.2.44-beta
  connectivity: 
  flutter_svg: ^0.19.1 # help us to use SVG in our app
  # provider: ^4.3.1

# --------------------------------
  uuid:
  firebase_database:

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - imgs/
    - assets/images/
    - assets/icons/ 
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

    # fonts:
    # - family: Muli
    #   fonts:
    #     - asset: assets/fonts/muli/Muli.ttf
    #     - asset: assets/fonts/muli/Muli-Bold.ttf
    #       weight: 700
    #     - asset: assets/fonts/muli/Muli-Light.ttf
    #       weight: 300
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
